### ISSUE TITLE
Don't works with onecheckout

### ISSUE THREAD

**Issue by raphaelcordeiro** [MagestyApps/magento2-fix-discount-rules#2]
I use OPCheckout from Rokanthemes and it don't works.

**Comment by benlau87** [comment]
I am also getting an error: 
"Warning: Illegal string offset 'method' in app/code/MagestyApps/FixRules/Controller/Checkout/ApplyPaymentMethod.php on line 53"

**Comment by MagestyApps** [comment]
We've refactored the payment method saving process in version 1.1.0. And we guess it should be working fine now with the 3rd party checkout module. Please, try pulling the latest version and checking the issue one more time. And then let us know the results. Thanks.

**Comment by MagestyApps** [comment]
Closing the issue due to inactivity
