### ISSUE TITLE
Magento 2.4

### ISSUE THREAD

**Issue by dearste** [MagestyApps/magento2-fix-discount-rules#4]
Installed in my 2.4, but not work at all. Is planned a fix?

**Comment by MagestyApps** [comment]
Hello,

We've just tested it under clean Magento 2.4.1 and it works fine. Could you please clarify what exactly is not working on your installation and provide a detailed instruction of how to reproduce the issue. Thanks.

**Comment by MagestyApps** [comment]
> Installed in my 2.4, but not work at all. Is planned a fix?

Hello,

We've just tested it under clean Magento 2.4.1 and it works fine. Could you please clarify what exactly is not working on your installation and provide a detailed instruction of how to reproduce the issue. Thanks

**Comment by MagestyApps** [comment]
Closed due to inactivity.
